apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/gateway

namePrefix: gateway-0-

configMapGenerator:
- files:
  - values.yaml=values.yaml
  name: gateway-values
