apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/influxdb

namePrefix: influxdb-0-

configMapGenerator:
- files:
  - values.yaml=values.yaml
  name: influxdb-values
